-- require 'vim-closetag'.setup {
--   closetag_filenames = '*.html,*.xhtml,*.phtml,*.svelte',
--   closetag_emptyTags_caseSensitive = 1,
--   closetag_shortcut = '>',
--   closetag_close_shortcut = '<leader>>'
-- }
-- 
